spring:
  datasource:
    url: jdbc:mysql://www.db4free.net:3306/finding_wizard
    username: viku8266
    password: Angel11@papa
  jpa:
    hibernate:
      ddl-auto: update

  spring:
    jpa:
      database-platform: com.mysql.cj.jdbc.Driver
server:
  port: 8081
kafka:
  producer:
    bootstrap:
      address: localhost:9092
